# Generated by Django 5.0.1 on 2024-06-19 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citation',
            name='auteur',
            field=models.CharField(choices=[('Noureddine Oubihi', 'Noureddine Oubihi'), ('Nolwenn Myran', 'Nolwenn Myran'), ('Damien Praca', 'Damien Praca'), ('Jérome Diaz-Rey', 'Jérome Diaz-Rey'), ('Valentin-Martin', 'Valentin-Martin'), ('Jérémy Gross', 'Jérémy Gross')], default='auteur', max_length=50),
            preserve_default=False,
        ),
    ]
