# Generated by Django 5.0.1 on 2024-06-26 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citations', '0003_alter_citation_auteur'),
    ]

    operations = [
        migrations.AddField(
            model_name='citation',
            name='score',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
